AppBundle\Entity\delivery;
  type:  entity
  table:  delivery
  id:
    id:
      type:  integer
      generator:  {  strategy:  AUTO  }
  fields:
    ref: string
      length: 255
      unique: true
    dateDelivery: datetime

