AppBundle\Entity\invoice;
  type:  entity
  table:  invoice
  id:
    id:
      type:  integer
      generator:  {  strategy:  AUTO  }
  fields:
    ref: string
      length: 255
      unique: true
    dateInvoice: datetime