AppBundle\Entity\Product:
  type:  entity
  table:  product
  id:
    id:
      type:  integer
      generator:  {  strategy:  AUTO  }
  fields:
    name:
      type: string
      length: 255
      unique: true
    description:
      type: string
      length:  255
      nullable:  true
    price:  float

    oneToMany:
      orderDetail:
        targetEntity: OrderDetail
        mappedBy: product
