app\CrudBundle\Entity\Invoice:
  type:  entity
  repositoryClass: app\CrudBundle\Repository\InvoiceRepository
  table:  invoice
  id:
    id:
      type:  integer
      generator:  {  strategy:  AUTO  }
  fields:
    ref:
      type: string
      length: 255
      unique: true
    dateInvoice: datetime
  oneToMany:
    delivery:
      targetEntity: Delivery
      mappedBy: invoice