app\CrudBundle\Entity\OrderDetail:
  type:  entity
  repositoryClass: app\CrudBundle\Repository\OrderDetailRepository
  table:  orderDetail
  id:
    id:
      type:  integer
      generator:  {  strategy:  AUTO  }
  fields:
    qte:
      type: float
  manyToOne:
    product:
      targetEntity: Product
      inversedBy: orderDetail
      joinColumn:
        name: product_id
        referencedColumnName: id
    command:
      targetEntity: Command
      inversedBy: orderDetail
      joinColumn:
        name: command_id
        referencedColumnName: id