app\CrudBundle\Entity\OrderDetail:
  type: entity
  repositoryClass: app\CrudBundle\Repository\OrderDetailRepository
  table: orderDetail
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    qte:
      type: float
  manyToOne:
    products:
      targetEntity: Product
      inversedBy: orderDetails
      joinColumn:
        name: product_id
        referencedColumnName: id
    commands:
      targetEntity: Command
      inversedBy: orderDetails
      joinColumn:
        name: command_id
        referencedColumnName: id